# Generated by Django 5.1 on 2024-09-06 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='orginal_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_post', to='post.post'),
        ),
    ]
