# Generated by Django 4.2 on 2024-09-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_orginal_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_repost',
            field=models.BooleanField(default=False),
        ),
    ]
