# Generated by Django 4.2.9 on 2024-09-25 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(blank=True, max_length=11, unique=True, verbose_name='phone number')),
                ('username', models.CharField(max_length=120, unique=True, verbose_name='username')),
                ('date_join', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='full name')),
                ('email', models.EmailField(max_length=300, unique=True, verbose_name='email')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar_user/%y/%m/%d', verbose_name='avatar user')),
                ('about_me', models.TextField(blank=True, max_length=1000, null=True, verbose_name='about me')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, verbose_name='gender')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-created', '-updated'),
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='code')),
                ('expired_date', models.DateTimeField(verbose_name='expired date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otpuser', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
