# Generated by Django 5.1 on 2024-08-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=300, verbose_name='full name')),
                ('email', models.EmailField(max_length=300, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=120, unique=True, verbose_name='username')),
                ('avatar', models.ImageField(upload_to='avatar_user/%y/%m/%d', verbose_name='avatar user')),
                ('date_join', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
