# Generated by Django 4.2.9 on 2024-09-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True, unique=True, verbose_name='email'),
        ),
    ]
