# Generated by Django 4.2.9 on 2024-10-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True, unique=True, verbose_name='email'),
        ),
    ]
