# Generated by Django 5.1 on 2024-08-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_user/%y/%m/%d', verbose_name='avatar user'),
        ),
    ]
